language: node_js
node_js:
  - "4.5"

#cache:
#  directories:
#    - $HOME/.npm
#    - $HOME/.yarn-cache
#    - node_modules

before_install:
  - time npm i -g yarn

install:
  - time yarn > /dev/null

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./nodeserver.sh > /dev/null &

script:
  - echo "CORE_BRANCH = x${CORE_BRANCH}x";
  # Fetch and build the ui-router-core branch from github, then install it
  - >
    if [ "x${CORE_BRANCH}x" != "xx" ] ; then
      echo "Installing ui-router-core from ${CORE_BRANCH}" && \
      git clone --depth=10 --branch="${CORE_BRANCH}" https://github.com/ui-router/core.git ui-router-core && \
      pushd ui-router-core && \
      yarn > /dev/null && \
      yarn build && \
      popd && \
      npm install ./ui-router-core ;
    fi
  - tsc && npm test

matrix:
  allow_failures:
  - env: CORE_BRANCH=

env:
  matrix:
    # CORE_BRANCH env variable specifies the branch of ui-router-core to use during build/test
    # Each CORE_BRANCH listed here will trigger a SEPARATE job in travis
    - CORE_BRANCH=master

    # If CORE_BRANCH is empty, it will use the ui-router-core from npm dependencies
    # (as specified in package.json)
    - CORE_BRANCH=

sudo: false

git:
  depth: 3

notifications:
  slack: angularbuddies:b6leQM9gkBCW0S7MNDsELpqU
